---
functional:
  - Позволить пользователям играть против другого человека или бота.
  - Определять победителя на основе правильности решения и времени, затраченного
    на его нахождение.
  - Обеспечить видимость редактора кода в реальном времени для обоих игроков.
  - Дать возможность видеть вывод тестов в реальном времени.
  - Разрешить смену языка программирования во время решения задачи.
  - Разрешить приглашение друзей в игру по ссылке.
  - Предоставить возможность выбора сложности игры до ее начала.
  - Предоставить возможность смены языка описания задачи.
  - Дать возможность наблюдать за играми других пользователей.
  - Реализовать регистрацию в приложении.
  - Реализовать функцию входа в приложение.
  - Предоставить текстовый чат для общения во время игры зарегистрированным
    пользователям.
  - Сохранять записи завершенных игр для пользователей.
  - Дать возможность завершить начатую игру.
  - Вести рейтинг пользователей за неделю, месяц и за всё время.
  - Записи завершенных игр не должны быть интерактивными.
  - Позволить пользователям создавать и редактировать свой профиль.
  - Дать возможность создавать задачи для решения.
  - Позволить создавать игровую сессию и решать задачи.
  - Платформа должна предоставлять чат для взаимодействия с другими участниками.
  - Пользователь должен иметь возможность выбирать параметры игры (уровень, тип
    игры, контроль времени, задачу по имени или тегам).
  - Пользователь может организовывать турниры.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Запись игры реализована в виде видео-проигрывателя.
implicit:
  - Для определения победителя необходимо реализовать счетчик времени.
  - Для обеспечения возможности видеть редактор оппонента в реальном времени
    необходимо реализовать оба редактора на одной странице.
  - Зарегистрированным пользователям необходимо предоставить выбор с кем играть,
    с ботом или человеком.
  - Необходимо реализовать возможность выбора игры для наблюдения.
  - Наличие темной темы.
  - Поддержка нескольких языков.
  - Пользователи не могут вносить изменения в рейтинг пользователей вручную.
